//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLITHUVIENWINFORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVContext : DbContext
    {
        public QLTVContext()
            : base("name=QLTVContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<The> Thes { get; set; }
        public virtual DbSet<Muon> Muons { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<ChiTietMuon> ChiTietMuons { get; set; }
        public virtual DbSet<YeuCauMuon> YeuCauMuons { get; set; }
        public virtual DbSet<ChiTietYeuCau> ChiTietYeuCaus { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
